### ISSUE TITLE
L2.T13- La funzione di interpretazione può associare piu elementi del dominio?

### ISSUE THREAD

**Issue by NiSHoW** [avillafiorita/cl-2020#1]
Premessa: Il video L2.T13.Introduction.LogicalModeling al minuto 10:10 mi salta (non so se è solo un mio problema) perdendo la spiegazione dell esempio 2 "Description Logic"

Nell frame sottostante si parla di slide corrette ma le slide sul sito sono uguali a quelle che si vedono nel video.
![image](https://user-images.githubusercontent.com/5220542/93394974-6229f380-f875-11ea-8437-13119a9a3cca.png)

Domanda: 
Nel 2 esempio e nel 3 gli esempi delle funzioni di interpretazione ritornano piu elementi del dominio,
Ma nella slide della prima lezione si parlava che la funzione di interpretazione deve associare a ogni elemento del linguaggio uno e uno solo elemento del dominio. 

![image](https://user-images.githubusercontent.com/5220542/93394868-2c850a80-f875-11ea-99d4-95ce3009fbb9.png)

Questa affermazione è scorretta?
Nel caso sia corretta, nell'esempio 3 ("First Order Logic"?) La cosa cambia perchè A è intesa come formula A(x)?
O questa affermazione è valida solo per le logiche decidibili (First Order Logic esclusa?)

Ringrazio

**Comment by avillafiorita** [comment]
Affrontata in L3. Proviamo a chiudere, eventualmente si riapre se ci sono ancora punti da chiarire
