### ISSUE TITLE
Esercizio riduzione in CNF

### ISSUE THREAD

**Issue by StefanoGenettiUniTN** [avillafiorita/cl-2020#13]
Buonasera.
Per esercizio ho provato a tradurre la seguente formula in CNF:

`¬((p→(q→r)))→((p→q)→(p→r)))`

A seguito di alcuni passaggi non riesco più a continuare nello svolgimento. Allego i vari passaggi che ho velocemente trascritto per maggiore chiarezza.

![image](https://user-images.githubusercontent.com/57845191/95687848-8378c800-0c06-11eb-975e-7d5e6ebf199c.png)

Non capisco come svolgere il prodotto cartesiano tra una congiunzione e una disgiunzione.
Nello specifico: `CNF((p ∧ ¬q) ⊗ (¬p ∨ r)) = ?`

Grazie per la disponibilità.

**Comment by avillafiorita** [comment]
pensavamo di aver risposto con l'esercizio e logictools, mancava forse un pezzo:

per l'applicazione della regola, dalle slide:

where (C1 ∧ ···∧ Cn ) ⊗ (D1 ∧ ···∧ Dm ) is defined as (C1 ∨ D1) ∧ ···∧ (C1 ∨ Dm ) ∧ ···∧ (Cn ∨ D1) ∧ ···∧ (Cn ∨ Dm)

Nel caso che pone, chiami D1 = (¬p ∨ r), dovrebbe diventare:

(p ∨ (¬p ∨ r)) ∧(¬q ∨ (¬p ∨ r))

mi faccia sapere se risponde, così ri-chiudo, se tutto chiaro.

**Comment by StefanoGenettiUniTN** [comment]
Adesso mi è chiaro, grazie mille.

**Comment by avillafiorita** [comment]
grazie, chiudo, allora.
