### ISSUE TITLE
L10.T76.FOL.Exercises

### ISSUE THREAD

**Issue by AlessandroTomazzolli** [avillafiorita/cl-2020#16]
Buonasera, 
volevo chiedere delucidazioni riguardo al metodo di risoluzione degli esercizi alla slide 2 (la prima tipologia di esercizi).

Grazie per la disponibilità, 
Alessandro Tomazzolli

**Comment by avillafiorita** [comment]
discusso nel video appena caricato L12.X.FOL.Exercises.
