### ISSUE TITLE
L8.X.1.PL.Exercises

### ISSUE THREAD

**Issue by Giunsky** [avillafiorita/cl-2020#17]
Scusi il disturbo ma ho un dubbio.
Al punto 1.1 non dovremmo avere **p imp (q imp p)** al posto di **(p imp q) imp p**?
![Screenshot 2020-10-19 152729](https://user-images.githubusercontent.com/72440400/96457962-addb0e80-1220-11eb-8f1a-ec883b106653.png)

Grazie per l'attenzione.

**Comment by avillafiorita** [comment]
nessun disturbo e ha ragione, le parentesi sono sbagliate.

sistemo le slide in serata; già che c'ero, ho risolto anche il tableaux
della formula con le parentesi "sbagliate". Pubblico anche questo
stasera, glielo propongo come esercizio, nel frattempo!

 cordialmente
 -a
