### ISSUE TITLE
L10.T76.FOL.exercises

### ISSUE THREAD

**Issue by Aless1234** [avillafiorita/cl-2020#18]
Buongiorno, 
volevo richiedere riguardo alla slide 3 come vanno affrontati esercizi come il punto 9, 11, 12 ,13 che presentano x=x oppure x=y.
Inoltre volevo chiedere sempre per la slide 3, la risoluzione del punto 2

Grazie
Buona giornata
Alessia

**Comment by avillafiorita** [comment]
risposto oggi, chiuderei: nel caso riapriamo
