### ISSUE TITLE
Iscrizione prova parziale

### ISSUE THREAD

**Issue by AlessandroTomazzolli** [avillafiorita/cl-2020#19]
Buonasera, 
volevo chiederLe delucidazioni riguardo la possibilità di iscriversi alla prima prova parziale che si terrà il prossimo 2 novembre, poiché non trovo indicazioni a riguardo e sulla bacheca di esse3 non compare tra gli esami. 

Grazie, 
Alessandro Tomazzolli

**Comment by avillafiorita** [comment]
appena pubblicato su Moodle, chiuederei.
grazie
