### ISSUE TITLE
ES_tris_logico

### ISSUE THREAD

**Issue by spock-vulcano** [avillafiorita/cl-2020#2]
[ES_tris_logico.zip](https://github.com/avillafiorita/cl-2020/files/5241407/ES_tris_logico.zip)

Buongiorno,

ho provato a fare l'esercizio. Mi scuso se la scrittura è poco chiara. Non so se ho veramente capito come venga fatto un modello logico...comunque aspetto martedì per la rivisione.

**Comment by avillafiorita** [comment]
buongiorno, mi scuso per la risposta così in ritardo: spero che lezioni registrate abbiamo aiutato a chiarire e, quindi, chiuderei, nel caso se ha dubbi specifici, riapriamo.
