### ISSUE TITLE
L11.T84.FOL - Practising with tableaux

### ISSUE THREAD

**Issue by bragg13** [avillafiorita/cl-2020#23]
Buongiorno, non riesco a capire la soluzione di un esercizio dalla slide come da titolo.
![image](https://user-images.githubusercontent.com/33253698/97013677-9914b880-1549-11eb-9106-8428a8e5ee06.png)

In particolare non mi è chiaro perchè la seconda riga del terzo nodo venga poi sviluppata al quarto nodo come notP(b); perchè non va bene notP(a)? E anche non fosse, come si arriva a quel quinto nodo?

Grazie,
Andrea Bragante

**Comment by AlessandroTomazzolli** [comment]
Provo a rispondere io, correggetemi se sbaglio: quando sostituisci nel "foreach" devi sempre usare una nuova variabile, mai una già utilizzata precedentemente nel tableaux. Il quinto nodo è poi la ripetizione del secondo ma con b al posto di a, in modo tale da poter valutare tutte le eventuali occorrenze discordanti di ogni variabile.

**Comment by avillafiorita** [comment]
... si, esatto: - Ax. P(x) è una delta rule e quindi richiede l'introduzione di un fresh term (non usato prima nel tableaux). Grazie ad Alessandro per la risposta e a bragg13 per la domanda. Ho messo anche una breve discussione nel video caricato ieri pomeriggio con gli esercizi FOL.
direi che possiamo chiudere, nel caso si riapre.
