### ISSUE TITLE
L11 T84

### ISSUE THREAD

**Issue by Sav22999** [avillafiorita/cl-2020#26]
Salve professore, non riesco a capire un passaggio.
Al secondo 16 (00:00:16)

![image](https://user-images.githubusercontent.com/32335378/97109188-094e4600-16d2-11eb-9926-2518b42b6751.png)

Nello specifico nell'ultimo passaggio, perché non sviluppiamo anche
![image](https://user-images.githubusercontent.com/32335378/97109204-1b2fe900-16d2-11eb-9e15-5a84f80ce77e.png)
in "not P(a)" così che si annulli con il "P(a)" superiore?

In pratica, perché ci si ferma solamente al "P(b)"?

**Comment by Sav22999** [comment]
È corretto continuare?

In questo modo:
![image](https://user-images.githubusercontent.com/32335378/97109240-5af6d080-16d2-11eb-83ea-fd6a86e15817.png)

**Comment by avillafiorita** [comment]
le rispondo al volo, perché questo è facile: trovata la prima
contraddizione siamo a posto. Se continua ne può trovare altre, ma non
serve.
faccia sapere se è sufficientemente chiaro o da approfondire
ulteriormente.
 -a

**Comment by Sav22999** [comment]
@avillafiorita capito, la ringrazio
