### ISSUE TITLE
formalizzazione in FOL

### ISSUE THREAD

**Issue by TudiFrudii** [avillafiorita/cl-2020#27]
Salve, facendo degli esercizi mi e' venuto un dubbio:
Ho visto sulle slide (slide 4 di L8.X.1.PL.Exercises) che "either" e' da considerare come una OR inclusiva, ma dall'inglese parlato mi verrebbe da assumere che si tratti di una OR esclusiva. 
Quindi "either" va interpretato come un OR esclusivo o un OR inclusivo? 

Grazie mille

**Comment by avillafiorita** [comment]
buongiorno -
a quanto ricordo dell'inglese, "either" può essere usato anche con
significato inclusivo
(https://www.merriam-webster.com/dictionary/either) ... quindi la
formalizzazione dipenderà dal significato che da alla frase e questo va
stabilito anche con il contesto.

"it is either blue or red" sarà probabilmente or esclusivo, "take
either road" sarà probabilmente or inclusivo.

**Comment by TudiFrudii** [comment]
capito, grazie mille
