### ISSUE TITLE
Esercizio formalizzazione PL

### ISSUE THREAD

**Issue by StefanoGenettiUniTN** [avillafiorita/cl-2020#28]
![image](https://user-images.githubusercontent.com/57845191/97463497-18d2c680-1940-11eb-8f3e-aeda09e240bf.png)

Buonasera.
In uno dei link da voi suggeriti nella sezione "Additional Materials" (https://www.cl.cam.ac.uk/teaching/1112/DiscMathI/exercises.pdf), ho trovato questo esercizio.
Come posso formalizzare in logica proposizionale le frasi (e) ed (f) ?

Grazie per la disponibilità.

**Comment by avillafiorita** [comment]
Esercizio (e)

Formalizzazione:
- walking in the path is safe = S
- berries are ripe along the path = B
- rabbits seen in the area = R

Significato di "Necessario ma non sufficiente":
- la condizione deve essere garantita, ma non basta ... anche se la condizione è vera, la conseguenza potrebbe non essere vera.

Proviamo allora a ragionare con la negazione:

- se la condizione necessaria non è garantita, allora siamo certi che camminare sul sentiero è pericoloso

... implicazione! (lascio il dettaglio a lei, ma eventualmente elaboro)

Esercizio (f)

Approccio simile al precedente, ma a questo punto siamo sicuri che quando la precondizione è soddisfatta (berry are ripe, rabbits have bee seen), allora camminare non è sicuro (not S). Confesso di non sapere se le precondizioni sono unite da un "and" (ambedue le condizioni devono essere soddisfatte) o da un "or" (basta uno dei due casi)... questo è un problema più linguistico, che logico, però.

Anche in questo caso le lascio completare l'esercizio, ma se serve elaboro.

**Comment by StefanoGenettiUniTN** [comment]
Grazie mille, credo di aver capito.

e)
(b or r) imp not w
o equivalentemente
w imp (not b and not r)

f) (b and r) imp not w

**Comment by avillafiorita** [comment]
bene!
