### ISSUE TITLE
Terzo assioma di Hilbert

### ISSUE THREAD

**Issue by ericsua** [avillafiorita/cl-2020#29]
Buonasera,
non mi torna il seguente assioma di Hilbert presente nel PDF L7.T52.PL.Reasoning.Hilbert.calculus
(¬ψ ⊃ ¬φ) ⊃ ((¬ψ ⊃ φ) ⊃ φ)
se in questo caso interpretassimo  I(ψ) = T e I(φ) = F, l'assioma risulta falso oppure sbaglio io?

**Comment by IvanValentini** [comment]
Si, hai ragione. Però mi sa che hanno fatto un'errore di scrittura. Nella slide L11.T81 riportano il terzo assioma così:
(¬ψ ⊃ ¬φ) ⊃ ((¬ψ ⊃ φ) ⊃ ψ), che di fatto è sempre vero.

**Comment by avillafiorita** [comment]
Grazie del commento e, a questo punto, della segnalazione dell'errore tipografico, che sistemiamo.

Chiaramente (ma qui siamo tutti d'accordo), gli assiomi di Hilbert sono formule valide e, quindi vere in ogni interpretazione. 

Incidentalmente l'assioma formalizza il fatto che se da una formula (negata) (¬ψ) possiamo derivare un'altra formula (φ) e il suo contrario (¬φ), allora la formula non negata deve essere vera (ψ) ... "Ammettiamo per assurdo che" ...

**Comment by ericsua** [comment]
Perfetto grazie ho capito! A questo punto però mi è venuto un dubbio su come interpretare "a parole" il secondo assioma
(φ ⊃ (ψ ⊃ θ)) ⊃ ((φ ⊃ ψ) ⊃ (φ ⊃ θ))

Grazie ancora

**Comment by avillafiorita** [comment]
hmm, su questo non riesco a trovare una formulazione compatta come nel caso precedente... direi: "se da una formula deduco una implicazione e dalla stessa formula derivo la premessa dell'implicazione, allora dalla formula sono in grado di derivare anche la conseguenza"
