### ISSUE TITLE
L2.T13.Introduction.LogicalModeling - L1.T11.Introduction.Modeling

### ISSUE THREAD

**Issue by StefanoGenettiUniTN** [avillafiorita/cl-2020#3]
Buonasera, credo di non aver compreso correttamente i seguenti due punti.

**L2.T13.Introduction.LogicalModeling SLIDE 11**

"A logic is decidable if there is an effective method for determining whether a formula is included in a theory"

Si intende che una logica è decidibile se esistono dei "criteri" per stabilire la correttezza o meno di teorie formulate con il linguaggio?

**L1.T11.Introduction.Modeling SLIDE 11**

"Truth-relation / entailment /satisfiability (⊨): a relation which associates what is true in the model with a subset of the sentence of the language. A sentence can be an element in a theory if and only if its interpretation is true in the model"

Non mi è molto chiaro cosa si intende con: "A sentence can be an element in a theory if and only if its interpretation is true in the model".

Grazie e buon fine settimana.

**Comment by avillafiorita** [comment]
Affrontato lezione 28/9 (si veda registrazione)
