### ISSUE TITLE
Formalizzazione di "Esattamente uno"

### ISSUE THREAD

**Issue by AlessandroTomazzolli** [avillafiorita/cl-2020#30]
Buongiorno, 
come dobbiamo comportarci nelle formalizzazioni di espressioni che contengono "Esattamente uno"?
Allego esempio e tentativo di soluzione: 

"Bill has exactly one sister"
Exists x. forall y.((sister(x,Bill) and sister(y,Bill)) imp x=y)

Può essere la precedente una soluzione valida? E nel caso, è possibile utilizzare and con l'esistenza e imp con il forall senza creare problematiche?

**Comment by avillafiorita** [comment]
mhhh... io qui formalizzerei con due universali (e la premessa dell'implicazione che limita le possibili interpretazioni).

forall x. forall y.((sister(x,Bill) and sister(y,Bill)) imp x=y)

con exists, dato un y che rende vero "sister(y,Bill))"  può sempre scegliere un termine "x" che falsifica "sister(x,Bill)" e la sua formula sarà vera. Con il forall, invece deve "confrontare" tutti i termini del suo dominio.

Per convincersi (o mettere in evidenza un mio errore!) provi a verificare la soddisfacibilità della due formule (quella con exists forall e quella con forall forall), in un dominio in cui Bill ha due sorelle.

**Comment by Sav22999** [comment]
@avillafiorita Con due universali il significato non sarebbe "al massimo una sorella"?

Con l'esistenza diciamo "qualcuno" (quindi sappiamo con esattezza che almeno uno esite), corretto?

**Comment by avillafiorita** [comment]
corretto, il doppio forall copre solo una parte. Appena mi libero ci
riprovo!

**Comment by avillafiorita** [comment]
la soluzione proposta qui mi sembra ben
fatta: https://math.stackexchange.com/questions/2210130/first-order-logic-only-one-construct

(la prima correzione che mi era venuta in mente: 

exist x. Sister(x, Bill) and forall y forall z (Sister(y, Bill) and
Sister(z, Bill) => y = z)

dovrebbe andare ugualmente bene, ma è un po' meno bella della soluzione
proposta su StackExchange)
