### ISSUE TITLE
Predicati e funzioni

### ISSUE THREAD

**Issue by AlessandroTomazzolli** [avillafiorita/cl-2020#31]
Buongiorno, 
all'interno delle slide del corso, in particolare al capitolo L9.T72.FOL.Language viene data la definizione di predicati e funzioni: tuttavia, all'interno di un esempio vengono poi distinti alcuni predicati che sembrano più simili a delle funzioni, e funzioni che sembrano più simili a dei predicati, dal punto di vista concettuale. 
Esiste una regola generale per capire quando un elemento va considerato come predicato piuttosto che come funzione?

**Comment by avillafiorita** [comment]
Provo a rispondere io. Non c'è una regola algoritmica, dipende dal suo dominio e dalla funzione di interpretazione e dall'approccio che sceglie per formalizzare. A seconda del caso, elementi del linguaggio con lo stesso nome potrebbero essere definiti come funzione  (se ci "interessa" il termine restituito dalla funzione) o come predicato (se ci interessa ragionare sul valore di verità).

Consideri i seguenti casi:

padre_di: funzione del linguaggio, ha arità 1, e "restituisce" il padre del termine passato come argomento. Ad es.

Costanti = {Mario, Giuseppe, Marta, Anna}
Lettere funzionali = {padre_di, madre_di}

padre_di(Anna) = Mario
padre_di(Giuseppe) = Mario

Un simbolo molto simile (PADRE_DI), però, potrebbe essere usato come predicato, se gli cambiamo l'arità e lo usiamo con il seguente significato: PADRE_DI è vero se il primo argomento è figlio/figlia del secondo argomento. 

In questo caso l'uso diventa:

PADRE_DI(Anna, Mario)
PADRE_DI(Giuseppe, Mario)

Noti che nella stessa formalizzazione potrebbe usare sia la funzione, sia il predicato. Consideri il seguente assioma:

forall x. forall y. ( PADRE_DI(x, y) iff padre_di(x) = y )

(Noti che il predicato, nella parte destra dell'iff è l'uguaglianza)

Spero  chiarisca, eventualmente elaboriamo.

**Comment by AlessandroTomazzolli** [comment]
Ho capito, grazie mille per la spiegazione chiara ed efficace
