### ISSUE TITLE
Scrivere un interpretazione soddisfacibile ed una insoddisfacibile per una formula data

### ISSUE THREAD

**Issue by momentino** [avillafiorita/cl-2020#32]
Buongiorno, nella sezione "materiali aggiuntivi" del sito ho trovato un link che portava a questa lista di esercizi: 
https://www.cs.upc.edu/~larrosa/MEI-CSI-files/SAT/SAT-exercises.pdf

Avrei una domanda riguardante questo esercizio:
11. Write a satisfying interpretation and a non-satisfying interpretation for the following formula,
(p∧(q∨r)∧ ¬(p∧q)∧ ¬(p∧r))∨(p∧ ¬r)

Attraverso le tabelle di verità oppure la costruzione di un tableaux posso verificare se la formula è soddisfacibile o meno.
Come potrei procedere per scrivere invece delle interpretazioni come richiesto dall'esercizio?

Penso di avere un attimo di confusione perchè penso che una formula sia o soddisfacibile o insoddisfacibile, non riesco a capire come possano esserci un interpretazione soddisfacibile e una insoddisfacibile per la stessa formula.

Grazie in anticipo,
Filippo.

**Comment by avillafiorita** [comment]
dovrebbe: 

1. rivedere i concetti di validità, non validità, soddisfacibilità, insoddisfacibilità e le relazioni con formula e sua negata.
2. rivedere la costruzione del Tableaux e la costruzione di un modello dato un Tableaux (rami aperti, verifica formule che appiaono attraversando l'albero, assegna T se lettera appare positivamente, F se lettera appare negativamente, ...)

sper sia di aiuto ... ma, davvero: dia un'occhiata alle slide, perché li si può chiarire le idee.  Nel caso siamo qui.

**Comment by momentino** [comment]
si ci ho riflettuto durante la giornata e la risposta era molto semplice. Credo di avere avuto un attimo di confusione e credevo che la risposta fosse più complicata. La ringrazio molto.
