### ISSUE TITLE
Come dimostrare l'ugualianza di "x=x"?

### ISSUE THREAD

**Issue by Sav22999** [avillafiorita/cl-2020#33]
In una lista di esercizi era richiesto di dimostrare "`x=x`"

![image](https://user-images.githubusercontent.com/32335378/97715411-a3433380-1ac2-11eb-8fea-72d15f3215a7.png)

Se non ho capito male, quando non è presente né _forall_ né _exists_ bisogna assumere la prima (`forall`). Ma in ogni caso non capisco come dimostrare `forall x.(x)=forall x.(x)`

Inoltre, se può anche illustrare queste altre tre formule (credo abbiano lo stesso principio)
![image](https://user-images.githubusercontent.com/32335378/97715639-eef5dd00-1ac2-11eb-8690-956a177795e6.png)

Nello specifico, ho provato a fare un tableau, ma non capisco come scomporre l'ugualianza. Non mi sembra di aver mai trovato una regola con `=` 😅

**Comment by avillafiorita** [comment]
Gli esercizi sono stati discussi alla sessione live L11, che abbiamo
appena caricato. Trova anche una discussione tra le issue chiuse.

Il tableaux la aiuta poco in questo caso. Deve definire la funzione di
interpretazione di "=" o aggiungere gli assiomi che codificano la
semantica dell'uguaglianza (tra cui, proprio, appunto, forall x. x=x).
Altrimenti e' come tentare di dimostrare la validità di P(x,x), cosa
che non può fare (mentre ne può verificare la soddisfacibilità con un
tableaux).

Chiuderei quindi questo (perche' duplicato), nel caso riapriamo.

**Comment by Sav22999** [comment]
Io e @AlessandroTomazzolli abbiamo visto insieme la lezione e, in realtà, non ci è molto chiaro il come effettivamente applicare e utilizzare la sostituzione.

Se potesse fare un esempio concreto, così magari è anche più chiaro.

Inoltre è corretto, allora, considerare un predicato `forall x forall y.ugualianza(x,y)` e considerarla una tautologia (quindi sempre vera)?

**Comment by Sav22999** [comment]
@avillafiorita ho appena trovato che sul libro consigliato (Logica 2a edizione, Varzi, Nolt e Rohatyn, McGraw Hill) è presenta questa definizione:

![image](https://user-images.githubusercontent.com/32335378/97782431-c4268a00-1b91-11eb-97da-571c080b0e94.png)

Quindi, essenzialmente, il libro dice di trattare l'ugualianza "normalmente" e di andare a sostituire le occorrenze di "y" con "x" (o viceversa), in quanto sono identiche.
