### ISSUE TITLE
Modelli e Contromodelli

### ISSUE THREAD

**Issue by AlessandroTomazzolli** [avillafiorita/cl-2020#34]
Buongiorno, 
mi rendo conto di non aver capito praticamente nulla di quanto concerne la ricerca di modelli e contromodelli per una formula una volta che il tableaux risulta aperto. 
Potrebbe rispiegare la cosa, magari con un paio di esempi? 
Grazie

**Comment by avillafiorita** [comment]
sentito giunchiglia, qui il consiglio è quello di rivedere slide e video della parte di teoria, dove queste cose sono state affrontate.
