### ISSUE TITLE
Sostituzione di x=y in un tableaux

### ISSUE THREAD

**Issue by AlessandroTomazzolli** [avillafiorita/cl-2020#35]
Buonasera, 
provando a fare l'esercizio numero 11 a pagina 2/3 della slide L10.T76.FOL.exercises ho riscontrato alcune difficoltà nel capire come  e quando effettuare la sostituzione di x=y all'interno del tableaux; inoltre, non ho ben chiaro se lo sviluppo del "se e solo se" va effettuata come prima cosa o come ultima cosa. 
Allego traccia per chiarire meglio quanto scritto: 

![Immagine](https://user-images.githubusercontent.com/44581548/97784034-f5a45300-1b9b-11eb-8e9c-84d237cd4511.png)

qui sotto allego invece un mio tentativo di risoluzione in cui mi sono arenato:

![image](https://user-images.githubusercontent.com/44581548/97784063-22f10100-1b9c-11eb-82e3-a02742e1d42b.png)

**Comment by LorenzoUniTN** [comment]
Avrei anch'io una domanda su questa tipologia di esercizi. Quando nel branch arrivo ad avere:
       
            P(x)
        not P(y)

e sapendo che come ipotesi avevo x=y, devo fare un'ulteriore passaggio come per esempio:

            P(x)
        not P(y)
           |
            P(a)
        not P(a)

prima di dire che il branch è closed siccome x e y si riferiscono allo stesso oggetto?

**Comment by Sav22999** [comment]
@LorenzoUniTN per come lo spiega il libro, in teoria è sufficiente che tu scriva

> P(x)
not P(x)

quindi andando a sostituire la "x" a "y" (o viceversa), perciò ottieni che il branch è chiuso.

Però potrei sbagliare 🤷‍‍♂️

**Comment by avillafiorita** [comment]
Guardando la struttura della formula riuscite anche a costruire Tableaux con maggiore confidenza.

Prima cosa da osservare: la conseguenza dell'implicazione (la formula con iff) è valida e, quindi, la premessa non "serve" a niente e non dovrebbe avere ruolo nello svolgimento del Tableaux. Quindi ci concentriamo sulla conseguenza.

Seconda cosa da osservare: se svolgete "iff" vi ritrovate con due formule molto simili:

not ( (forall x. P(x) imp forall y. P(y)) and (forall y. P(y) imp forall x. P(x)) )

Se svolgete "not ... and ..." vi ritrovate ramo di sx uguale al ramo di dx (salvo il nome della variabile quantificata universalmente... e, conseguentemente, lo svolgimento del ramo di DX sarà uguale a quello di SX. Potete quindi focalizzare su un solo ramo e poi "copiare" lo svolgimento del ramo di SX nel ramo di DX.

Svolgimento del ramo di sx procede come segue:

```
not  (forall x. P(x) imp forall y. P(y))
           |
forall x. P(x)
not forall y. P(y)
           |
forall x. P(x)
exists y. not P(y)
           |
       not P(a)
           |
        P(a) [da forall x. P(x)]
          | 
          X


```

**Comment by LorenzoUniTN** [comment]
Si poteva anche non fare il passaggio da "not forall y. P(y)" a "exists y. not P(y)" e scrivere direttamente

    forall x. P(x)
    not forall y. P(y)
           |
       not P(a)
           |
        P(a) [da forall x. P(x)]
          | 
          X

o risulta sbagliato per qualche motivo?

**Comment by avillafiorita** [comment]
preferisco non saltare i passaggi, ma, certo, una volta capita la regola nulla le vieta di fare qualche operazione a mente
(ma nel compito: tutti i passaggi, a scanso di equivoci o, comunque, spiegare che cosa si sta facendo).
