### ISSUE TITLE
Come svolgere la conseguenza logica nei CNF

### ISSUE THREAD

**Issue by Sav22999** [avillafiorita/cl-2020#36]
Salve professore.
Sto provando a risolvere questo esercizio:

La consegna richiede di verificare usando DPLL se _hold_ la conseguenza logica

![image](https://user-images.githubusercontent.com/32335378/97784843-a5c88a80-1ba1-11eb-9a5c-ed1d9d737bf0.png)

Il mio problema sorge quando devo sviluppare la conseguenza logica.

Nei tableaux lo svilupperei come se fosse un AND e ciò che segue (la "conseguenza") è negata.
Nei CNF, invece, come dovrei comportarmi?

Ho anche provato a svolgere come CNF(A and B and notA), e mi viene soddisfacibile, ma forse è CNF(A and B and A)=>CNF(A and B) che viene anche soddisfacibile.

**Comment by avillafiorita** [comment]
Teorema correttezza e completezza.

Tenga presente che  la trasformazione in CNF è semplicemente la riformulazione di una formula in un altra, equivalente e questo penso sia stato affrontato a teoria. 

Quindi può (e deve) separare i due concetti: 

1. può usare la trasformazione in CNF per semplificare le sue attività di deduzione (semi)automatica. Peraltro, una volta che ha una formula in CNF può usare DPLL.
2. discorso del tutto "ortogonale" è il motivo per cui usa la CNF. In questo caso intervengono le definizioni di validità, derivazione da una teoria, etc. e queste regole determinano se usa la formula o la sua negata.

Ambedue le questioni sono state affrontate a teoria. 
Chiudo, evntualmente riapriamo.
