### ISSUE TITLE
Esercizi L11.T84

### ISSUE THREAD

**Issue by IvanValentini** [avillafiorita/cl-2020#37]
Sto facendo gli esercizi di pagina 6,
![image](https://user-images.githubusercontent.com/34308333/97844228-f1d31680-1cea-11eb-8539-12c460d3f937.png)

e ho un dubbio sul secondo esercizio, che significato ha il simbolo ⊨ all'inizio dell'espressione?
Il primo esercizio mi è risultato il seguente tableaux:
![img](https://user-images.githubusercontent.com/34308333/97844783-ec2a0080-1ceb-11eb-9ab9-d4ffdfcdbb78.png)

E quindi ¬∃x (¬P(x) ∧ ¬Q(x)) è conseguenza logica di ∀x.P(x) ∨ ∀x.Q(x), è corretto?

**Comment by avillafiorita** [comment]
che significato ha il simbolo ⊨ all'inizio dell'espressione? -> **TEORIA!!!!**
(peraltro non so come abbia fatto a partire con il tableaux, senza sapere il significato di ⊨ ;-))

Il tableaux è corretto. Se pensa all'interpretazione delle formule, a mio giudizio, riesce a convincersi in maniera ancora più decisa.
