### ISSUE TITLE
Prenotazione Esame su Esse3

### ISSUE THREAD

**Issue by PietroFronzaUniTn** [avillafiorita/cl-2020#39]
Buongiorno
ho notato che è stato reso disponibile su Esse3 la prenotazione per la prova intermedia di venerdì 6 novembre 2020.
Dobbiamo iscriverci all'esame anche lì o basta aver compilato il form che avete reso disponibile su Moodle la scorsa settimana?
Ringrazio in anticipo per la risposta e vi auguro buona giornata

**Comment by avillafiorita** [comment]
ottima domanda, verifico e la faccio sapere. 
Non dovrebbe essere necessario registrarsi, ma le confermo.
-a

**Comment by avillafiorita** [comment]
abbiamo proceduto in maniera diversa e vi abbiamo iscritto direttamente usando i dati che avete inserito nel form.
oggi inviamo le istruzioni per verificare che sia tutto a posto per poter svolgere l'esame (collegamento, respondus, ecc)
