### ISSUE TITLE
Dubbio sull'ordine/priorità dei segni

### ISSUE THREAD

**Issue by Sav22999** [avillafiorita/cl-2020#40]
Ho un dubbio sulla priorità dei segni.
Ha più importanza "iff" o "implicazione"?
Perché, mi sembrava che in una lezione fossero riportante in questo ordine:
(1) not, (2) and, (3) or, (4) implicazione e (5) iff

Quindi, ad esempio, avendo questa formula:
x=y imp forall x . P(x) iff forall y . P(y)

devo considerarla come
(A) (x=y imp forall x . P(x)) iff forall y . P(y)
(B) x=y imp (forall x . P(x) iff forall y . P(y))

**Comment by avillafiorita** [comment]
esatto, le slide davano esattamente quella priorità, anche se, secondo
altre convenzioni iff e imp hanno la stessa priorità (quindi ordine di
lettura).

secondo quando abbiamo detto a lezione, vale la (A).
