### ISSUE TITLE
L9.T72.FOL.Language - page 10, Common Mistakes

### ISSUE THREAD

**Issue by jhonatha-asimov** [avillafiorita/cl-2020#42]
Non ho capito bene la differenza tra 
`exists x ( WorksAt(FBK, x) imp Smart(x) )`
e 
`exists x ( WorksAt(FBK, x) and Smart(x) ) `

**Comment by avillafiorita** [comment]
slide e video di giunchiglia, mi sembra abbia descritto la differenza,
ricordo male?

**Comment by jhonatha-asimov** [comment]
Si la ho ascoltata pero' non mi sembra sia stata chiara come nel punto sopra (universale + implica)
