### ISSUE TITLE
Formalizzazione di "esattamente uno" e "solo uno"

### ISSUE THREAD

**Issue by Aless1234** [avillafiorita/cl-2020#43]
Buongiorno,
volevo chiedere, nella logica del primo ordine se in una frase da formalizzare troviamo la dicitura "esattamente uno" e "solo uno" sono esse da considerarsi equivalenti? E in caso come possiamo formalizzarli? ( avevo letto la risposta in cui le veniva chiesta la formalizzazione di esattamente uno,ma non ho capito quale fosse la risposta)
Grazie

Buona giornata

**Comment by avillafiorita** [comment]
direi di sì sulla parte in italiano.

Per la formalizzazione Giunchiglia aveva discusso l'approccio in un
video.
