### ISSUE TITLE
L11.T84 Esercizi Logical Consequence

### ISSUE THREAD

**Issue by davidesartori** [avillafiorita/cl-2020#44]
Ho un dubbio, l'interpretazione e lo svolgimento dell'esercizio sono corretti?

![tableau](https://user-images.githubusercontent.com/32146083/98023312-03114580-1e07-11eb-8284-80ab61a7bd50.jpeg)

**Comment by Sav22999** [comment]
@davidesartori in teoria i due rami a destra sono chiusi perché:
- nel 1° branch: hai `P(a)` e poi, alla fine, `notP(a) and notQ(a)` (alla quale applichi la _alpha rule_), e puoi notare che `P(a)` e `notP(a)` fanno chiudere il ramo (è una `and`, quindi non ti serve trovare la chiusura anche di `notQ(a)`
- nel 2° branch: hai praticamente la stessa cosa del 1° ma con `Q(b)`

Spero di non aver detto una cosa non vera

**Comment by avillafiorita** [comment]
si, corretto.

**Comment by davidesartori** [comment]
Ok, grazie mille
