### ISSUE TITLE
Domanda quantificatori FOL (allego risposta già fornita dal docente) 

### ISSUE THREAD

**Issue by nicolazilio0** [avillafiorita/cl-2020#45]
o una domanda relativa ai quantificatori della Firts Order Logic:
se devo trasformare in formal la frase : "Everyone likes Mary except from Mary herself"
esiste un modo per fare una restrizione sul quantifier FORALL mettendo un eccezione per Mary? 
Una possibile soluzione può essere scrivere FORALL x . (likeasMary(x) AND NOT likesMary (Mary)) ?

RISPOSTA: 

la formula che ha scritto non va bene, perche' Mary e' libera per x e quindi, il quantificatore universale non ha effetto.
poi: restrizioni sul dominio come premessa dell'implicazione

quindi, direi:

forall x. (x != Mary imp likesMary(x))

ERRATA CORRIGE PRIMA RISPOSTA

perche' quando x è proprio Mary, la premessa è falsa e nulla possiamo concludere su likesMary(x) (e quindi lasciamo aperte le due interpretazioni, inclusa quella in cui  likesMary(Mary). Bisogna restringere ulteriormente aggiungendo and not likesMary(Mary).

quindi:

	forall x. (x != Mary imp likesMary(x)) and not likesMary(Mary)

oppure

	forall x. (likesMary(x) -> x != Mary)

**Comment by avillafiorita** [comment]
Nella formula Mary è libera per x e quindi, il quantificatore universale non ha effetto. La prima deve essere vera per ogni x e, quindi, la formula è inconsistente.

Possiamo approcciare con una implicazione con premessa che restringe il dominio:

  forall x. (x != Mary imp likesMary(x))

La formula, però non è completa, perche' quando x è proprio Mary, la premessa è falsa e nulla possiamo concludere su likesMary(x) (e quindi lasciamo aperte le due interpretazioni, inclusa quella in cui  likesMary(Mary). Bisogna restringere ulteriormente aggiungendo 

  not likesMary(Mary).

quindi:

  forall x. (x != Mary imp likesMary(x)) and not likesMary(Mary)

alternativamente:

	forall x. (likesMary(x) <-> x != Mary)

(notare iff, implicazione non basta)
