### ISSUE TITLE
Hilbert assioma 3

### ISSUE THREAD

**Issue by AlessandroColomboUnitn** [avillafiorita/cl-2020#47]
Buongiorno, riducendo in CNF il terzo assioma di Hilbert ho notato che la formula risultante era non valida. Costruendo la tabella di verità ho notato che con l'interpretazione φ=F, ψ=T l'assioma di partenza risulta falso (anche Tree Proof Generator da lo stesso risultato). Come è possibile? Gli assiomi di Hilbert non dovrebbero essere validi?  
Grazie per l'attenzione e buon pomeriggio.

**Comment by avillafiorita** [comment]
si, naturalmente, gli assiomi di Hilbert sono validi. Le slide avevano
un errore tipografico, segnalato da alcuni studenti. 

C'è una issue che discute la questione, deve cercare tra quelle chiuse.

 -a
