### ISSUE TITLE
svolgimento esercizi L13.T104.ML.VAL2LE

### ISSUE THREAD

**Issue by TudiFrudii** [avillafiorita/cl-2020#49]
Buongiorno, 
ho trovato difficoltà nello svolgimento degli esercizi sulle slide 6, 7 e 8 del pdf L13.T104.ML.VAL2LE. 
Chiedo cortesemente di fornire un esempio di procedimento da seguire per la risoluzione dei quesiti (possibilmente uno per tipo).
Grazie in anticipo

**Comment by avillafiorita** [comment]
caricati sul sito
