### ISSUE TITLE
Tic-tac-toe precisazione

### ISSUE THREAD

**Issue by matteo-crypto** [avillafiorita/cl-2020#5]
1.
Se assumo vera la formula proposizionale X3 ∧ O1 ∧ X7 ∧ O5 ∧ X9 ∧ O6 ∧ X8, dove le croci vincono, allora, volendo definire un modello, tra le tanti possibili interpretazioni del dominio, che rispetti l'etica/ le regole del gioco, un possibile modello sarebbe I(X3)=T, I(O3)=F, I(O1)=T, I(X1)=F, I(X7)=T, I(O7)=F, I(O5)=T, I(X5)=F, I(X9)=T, I(O9)=F, I(O6)=T, I(X6)=F, I(X8)=T, I(O8)=F, I(X2)=F, I(O2)=F, I(X4)=F, I(O4)=F. Quindi è possibile definire una sorta di protocollo affinché, a partire da formule proposizionali che assumo vere, si costruisca un modello che sia in linea con quanto detto prima e questo protocollo sarebbe: una cella può essere occupata da un solo simbolo e le celle vuote devono essere mantenute vuote. Ho così dato un procedimento generale, nella fase di modellazione, per garantire univocità.
Tutto ciò è corretto?

2.
Volendo definire una relazione nextMove, per poter rappresentare una partita nel contesto della logica proposizionale, è corretto quanto segue?
nextMo∨e ⊆ {X,O} x {1,2,3,4,5,6,7,8,9} 
I(nextMo∨e) = →
→ () = {X,O} x {1,2,3,4,5,6,7,8,9}
→ (X3) = O1 ∨ O2 ∨ O4 ∨ O5 ∨ O6 ∨ O7 ∨ O8 ∨ O9
→ (X3 ∧ O1) = X7 ∨ X2 ∨ X4 ∨ X5 ∨ X6 ∨ X8 ∨ X9
→ (X3 ∧ O1 ∧ X7) = O5 ∨ O2 ∨ O4 ∨ O6 ∨ O8 ∨ O9
→ (X3 ∧ O1 ∧ X7 ∧ O5) = X9 ∨ X2 ∨ X4 ∨ X6 ∨ X8
→ (X3 ∧ O1 ∧ X7 ∧ O5 ∧ X9) = O6 ∨ O2 ∨ O4 ∨ O8
→ (X3 ∧ O1 ∧ X7 ∧ O5 ∧ X9 ∧ O6) = X8 ∨ X2 ∨ X4
→ (X3 ∧ O1 ∧ X7 ∧ O5 ∧ X9 ∧ O6 ∧ X8) crosses win

**Comment by avillafiorita** [comment]
Linguaggio:

leggermente meglio X_i where i >= 1 and i <= 9 

{X,O} x {1,2,3,4,5,6,7,8,9} -> {(X, 1), (X, 2), ...}

Un altro modo di specificare la "fairness" consiste nell'esprimere i vincoli nella teoria:

not (X_1 and O_1)
not (X_2 and O_2)

Inoltre notare che la logica proposizionale riesce ad esprimere lo stato di una board in un preciso istante.

Per capirlo provate ad immaginare la situazione in cui modelliamo anche il fatto che una cella sia vuota, usando E_1. È evidente che dovrei dire:

E_1
not ((X_1 or O_1) and E_1)

Nel momento in cui metto una X nella casella 1, la mia teoria "diventerebbe":

E_1
not ((X_1 or O_1) and E_1)
X_1

dando luogo ad una teoria inconsistente, in cui posso dimostrare tutto e il suo contrario.

Se voglio modellare una partita, ad ogni mossa equivalentemente:

- è come se aggiungessi un nuova formula nella mia teoria... questo però cambia la teoria da una teoria al momento t a ad una teoria al momento t+1
- è come se modificassi la mia funzione di interpretazione ... cambiando, ancora una volta, dal tempo t al tempo t+1

**Comment by avillafiorita** [comment]
Affrontato lezione 28/9 (si veda registrazione)
