### ISSUE TITLE
L17.X2.ML.Frames

### ISSUE THREAD

**Issue by Aless1234** [avillafiorita/cl-2020#55]
Buongiorno, volevo chiedere, nel mondo indicato dalla freccia rossa, non sarebbe più corretto scrivere diamond not phi, invece di not diamod phi? oppure le scritture sono equivalenti?
![Cattura](https://user-images.githubusercontent.com/72376368/100865509-b79a9780-3497-11eb-8491-f5ffb1720517.PNG)

**Comment by avillafiorita** [comment]
Buonasera,
le due scritture non sono equivalenti (potrebbe provare a dimostrarlo, peraltro)... comunque:

- not diamond phi -> non è possibile che -> i tutti gli stati raggiunti deve valere not phi
- diamond not phi -> è possibile che non -> in almeno uno stato raggiunto vale not phi

Mi sembra sia giusto nell'esercizio:

1. nego la conseguenza nello stato 1: not box diamond phi -> diamond **not diamond phi**. Quindi in uno degli stati raggiunti vale **not diamond phi**

vado a memoria, quindi spero di ricordare bene che cosa stavo scrivendo... nel caso basta un ulteriore commento. Se invece è chiaro, chiudiamo.
