### ISSUE TITLE
Esercizio formalizzazione DL

### ISSUE THREAD

**Issue by TudiFrudii** [avillafiorita/cl-2020#56]
Buongiorno, ho dei dubbi riguardo la formalizzazione della seguente proposizione: 

“There are two kinds of birds: those that fly and those that do not. Birds are animals having wings. Penguins are birds that do not fly. Willy is a penguin.”

in particolare personalmente scriverei:

-> TBox
t1) Bird ≡ Flying ⊔ ¬Flying
t2) Flying ⊑ Bird
t3) ¬Flying ⊑ Bird
t4) Bird ⊑ Animal ⊓ WithWings
t5) Penguin ⊑ ¬Flying
-> ABox
a1) Penguin(Willy)

di tutto cio' non sono convinta delle espressioni t1,t2 e t3 perche' mi sembrano ridondanti. La mia formalizzazione e' sbagliata? Potrei risolvere in un modo piu' compatto?

Grazie in anticipo

**Comment by avillafiorita** [comment]
le anticipiamo che il suo dubbio è fondato. Noti anche che si ritrova anche una defizione con A or not A, che ha come estensione l'universo.

Lo vediamo assieme domani a lezione (o in video registrato).

**Comment by avillafiorita** [comment]
Risposto con video caricato questa mattina L21.X2... Chiuderei, riapriamo se non è chiaro.

Attenzione che questa definizione:

Bird ≡ Flying ⊔ ¬Flying

include l'universo, inclusi "marmotte", "aeroplani", ... (sul video è spiegato).
