### ISSUE TITLE
Esercizio espansione DL

### ISSUE THREAD

**Issue by FabrizioSandri** [avillafiorita/cl-2020#57]
Buongiorno, avrei un dubbio nella risoluzione del seguente esercizio.

Supponiamo di avere le seguenti TBox ed Abox:
```
TBox = {A ≡ ¬B ⊓ ¬C, B ≡ D ⊓ ¬C} 
ABox = {¬B(a), A(a)}
```

Espandiamo ¬B(a) nell'ABox come segue
```
¬B(a)
(¬(D ⊓ ¬C))(a)
(¬D ⊔ C)(a)
```

Espandiamo A(a) nell'ABox come segue
```
A(a)
¬B(a)
¬C(a)
```

Il mio dubbio ora è: come posso procedere con l'espansione di (¬D ⊔ C)(a) ? Devo fare uno split? in tal caso come posso farlo?

Se in questo caso mi venisse chiesto se l'espansione dell' ABox è consistente rispetto alla TBox, dovrei rispondere che non lo è in quanto nell'espansione dell'ABox ho sia (¬D ⊔ C)(a) che ¬C(a)  ?

La ringrazio in anticipo per la disponibilità

**Comment by avillafiorita** [comment]
svolto a lezione domani 7/12 (o, comunque caricato in video)

**Comment by avillafiorita** [comment]
questo esercizio è stato sviluppato in classe, in ogni caso nell'espansione di A deve espandere B per poter portare a termine l'espansione.
