### ISSUE TITLE
Implicazione

### ISSUE THREAD

**Issue by notyourbusiness-afk** [avillafiorita/cl-2020#6]
Non mi è molto chiaro il concetto di implicazione. 

Se A = False e B = True. 
A->B è True o False? e B->A?

**Comment by avillafiorita** [comment]
```
A B (A->B)
F F T
F T T
T F F
T T T
```

In altre parole:

- se la **premessa è falsa**, allora la **conseguenza può essere vera o falsa**
- se la **premessa è vera**, allora la **conseguenza deve essere vera, perchè l'implicazione sia vera**. 

Se la difficoltà nasce dagli stessi dubbi che avevo quando ho studiato logica proposizionale, deve considerare che, nel ragionamento informale, tendiamo a  ragionare sempre con una premessa vera e ad assumere le implicazioni come vere. I casi più "rognosi" quindi sono

    V -> F (implicazione non valida)
    F -> V (uno dei casi con premessa falsa).

Il primo si spiega come segue: non posso affermare che da qualcosa di vero posso dedurre qualcosa di falso. Questo a meno di una teoria inconsistente, ma in una teoria inconsistente, come anche scritto nelle slide, si deduce tutto, ossia per ogni formula A, sia A sia (not A). 

Esempio:

> Assumiamo di avere la seguente implicazione "Se (1 == 1) allora (1 == 2)" Assumere questa implicazione come vera vuole dire essere in grado di dedure tutto, ossia di avere una teoria inconsistente (= una teoria senza modelli).

La seconda si spiega come segue: da una premessa falsa posso derivare tutto e il contrario di tutto, che ci riporta al caso precedente. Ossia siamo in presenza di una teoria inconsistente.“se oggi piove a New York allora io gioco in borsa” 

Per concludere consideri questo esempio, che riflette meglio l’uso concreto della implicazione:

> "Se domani fai trenta gol alla partita, allora ti do un milione di euro" 

... l'implicazione è vera, ma non sarò mai in grado di usarla nei miei ragionamenti (o di darne seguito), perché non sarò in grado di rendere vera la premessa (immaginando, naturalmente, che nessuno sia in grado di segnare 30 goal in una partita). 

Questa è la situazione tipica delle implicazioni. Al netto delle teoria inconsistenti, esse agiscono e possono essere utilizzate nel ragionamento solo nel caso in cui le loro premesse sono vere. Tutte le implicazioni con premesse false, pur rimanendo vere, sono, di fatto, inutilizzabili. Così come sono inutilizzabili tutte le implicazioni in cui non è possibile (con un processo di ragionamento o di verifica sperimentale) asserire la verità delle premesse. Pensi ad esempio alla frase “se oggi piove a New York allora io gioco in borsa” detta da una persona che non è in grado di sapere il tempo a New York. Un frase che possiamo assumere vera me che non potrà mai essere utilizzata.

Spero sia chiaro, eventualmente basta aggiungere un commento a questa spiegazione.

  cordialmente
  -av e fg
