### ISSUE TITLE
L19 T165 pag 8

### ISSUE THREAD

**Issue by Sav22999** [avillafiorita/cl-2020#60]
Nel linguaggio naturale (NL) viene detto "Is there any animals which is **not** a horse **nor** a mule, ...".
Con @AlessandroTomazzolli ci stavamo ragionando e abbiamo interpretato "not" ... "nor" come "né" ... "né", ovvero nessuna delle due deve essere vera.
Tuttavia, nel DL viene riportato come "not(Horse and Mule)" e ciò, per regola di De Morgan (e facendo anche una tabella di verità), viene fuori "(notHorse or notMule)", ovvero che se solo una delle due è vera, alla tutto è vero.
Vorremmo capire, perciò, se è stato commesso un errore di trascrizione e invece di "not(H and M)" sarebbe dovuto essere "notH and notM".

**Comment by Sav22999** [comment]
Il prof. Giunchiglia mi ha risposto nella diretta di oggi, ed effettivamente è un errore delle slide.
La forma corretta è "not(H or M)" oppure, equivalentemente, "not(H) and not(M)".

**Comment by LorenzoUniTN** [comment]
Quindi l'esercizio risulta solo inconsistente alla fine e non o inconsistente o consistente in base al caso giusto?
