### ISSUE TITLE
Questio L21.X2.DL.I2F-and-Reasoning-small 

### ISSUE THREAD

**Issue by FabrizioSandri** [avillafiorita/cl-2020#61]
Riguardo all secondo esercizio di oggi a minuto 20:10 procede espandendo l'Abox ottenendo come risultato
Penguin(w)
NFB(w)
not F(w)

Successivamente al minuto 21:30 ripete l'esercizio ottenendo la seguente espansione:
Penguin(w)
NFB(w)
not F(w)
Animal(w)
Winged(w)

Non mi è chiaro perchè effettua queste due diverse espansioni distinte.

Inoltre vorrei chiederle il motivo per cui dice che Bird(w) non appartiene all'espansione dell'Abox.
La ringrazio in anticipo.

**Comment by avillafiorita** [comment]
Buonasera, grazie per la segnalazione... in effetti è rimasta una parte che avrei dovuto tagliare (non le abbiamo conservate, ma ce ne sarebbero di "paperissima" da inserire a fine corso).

Quindi: buono l'esercizio dal minuto 21:30 (nota per chi leggerà nei prossimi giorni: il file è stato editato e la parte inutile rimossa).

Non inserisco Bird perché è una definizione non primitiva (Bird è definito in termini di NFB e FB). Così almeno è come ho intepretato: http://datascientia.education/cl-2020/material/L18.T156.DL.TBox-ABox.ABox.reasoning.pdf, slide 4:

    The expansion A’ of A with respect to T contains only primitive (not defined concepts)

Verifico con calma, comunque e eventualmente mi riservo di correggere quanto le ho detto (riaprendo la issue).

La riapra lei, intanto, se qualcosa non è chiaro.

  grazie!
