### ISSUE TITLE
dubbio su mondo non seriale e necessita'

### ISSUE THREAD

**Issue by TudiFrudii** [avillafiorita/cl-2020#62]
Buongiorno, 
non mi e' chiaro perche' avendo un frame non seriale, in particolare considerando un mondo isolato w (quindi w tc ∄v.R(w,v)) si possa dire che w ⊨  □φ (1), qualunque sia la  φ ma non w ⊨  ◊φ (2). 
In particolare per la prima (1), non essendo presenti mondi accessibili, come fa un'affermazione ad essere necessaria?

**Comment by avillafiorita** [comment]
buongiorno,

mi sembra strano che nell'ipotesi che fa si possa dire w ⊨ □φ, a meno 
che R non sia riflessiva, nel cui caso dovrebbero valere ambedue 
(necessario e possibile).

Dove ha trovato il riferimento?

     grazie

**Comment by TudiFrudii** [comment]
al punto 3 della slide 5 di L14.T115.ML-K.More.ModalKD non capisco perche' valga w ⊨ □φ. 
Noto ora rileggendo che vale w ⊨ ◊φ, errore mio nella lettura. 
![Capture](https://user-images.githubusercontent.com/61164007/101602721-d13f6000-39fe-11eb-9b32-1e11d4479557.JPG)

**Comment by avillafiorita** [comment]
è, in effetti, un caso limite che deriva dalla definizione di □ (quello, appunto in cui non ci sono mondi successori). Intuitivamente la spiegherei come: "in un mondo che non c'è, è vero tutto e il suo contrario"... ma l'intuizione è pericolosa in logica. Lascerei a Giunchiglia la spiegazione di dettaglio. 

Alcuni testi distinguiono il caso particolare introducendo il concetto di "vacuously true at w".

**Comment by avillafiorita** [comment]
dopo un'interessante discussione con fausto eccoci qui con chiarimenti ed errata corrige.

ERRATA CORRIGE. Il punto 4 della slide è sbagliato, in realtà, se W non ha successori,  diamond phi non vale (abbiamo corretto slide, pubblichieremo nuova versione sul sito... la slide ha una dimostrazione un po' contorta, a mio giudizio e probabilmente ci si è dimenticati sul punto 4 il fatto che si stesse ragionando per assurdo)

Il motivo per cui vale "box phi" ma non "diamond phi" è il seguente. Sull'insieme vuoto forall non da problemi: posso tranquillamente ragionare su tutti gli elementi dell'insieme vuoto... non ce n'è neanche uno; l'esistenziale, invece, richiede di trovare un elemento (almeno un mondo) ... ma questo non riusciamo a trovarlo, perché l'insieme è vuoto. Conseguentemente BOX phi è vera perché in tutti i mondi successori (insieme vuoto, per ipotesi), vale phi. Invece DIAMOND phi è falso, perché non riesco a trovare un mondo in cui vale phi.

Quindi, sull'insieme vuoto, la nozione intuitiva che exists sia un "sottoinsieme" di forall non va regge.

Il motivo per cui, a mio giudizio, la dimostrazione è contorta, è che ragionando sul caso positivo (non per assurdo), la dimostrazione dell'implicazione è molto più intuitiva (se vale box phi, allora c'è almeno un mondo successore in cui vale phi e, conseguentemente vale diamond phi).

Grazie per la domanda, ho imparato anch'io qualcosa.

 Se a posto, chiuda lei la issue

**Comment by avillafiorita** [comment]
La nuova versione delle slide è caricata sul sito, a questo punto chiuderei, eventualmene riapriamo
