### ISSUE TITLE
L21 X1, KG2DL

### ISSUE THREAD

**Issue by Sav22999** [avillafiorita/cl-2020#64]
Avrei un dubbio sulla lezione 21, nello specifico quando vengono elencate le Relations nello Schema Level.
Con @AlessandroTomazzolli riflettevamo che, negli "attributes" (sempre di SL), viene scritto sia il nome dell'attributo, sia che cosa contiene (ovvero, ad esempio: `frequenza(stazione, integer)`.

Non dovrebbe scrivere anche cosa contengono le relazioni, ad esempio: `passa_per(linea, stazione)`?
Lei ha scritto solo `passa_per`, quindi vorremmo capire se possono essere utilizzate entrambe le notazioni oppure una è più giusta dell'altra.

Grazie.

**Comment by avillafiorita** [comment]
buonasera -

immagino sia al minuto 26, dove, in effetti, sono inconsistente nell'uso 
della notazione:

- per le relazioni inserisco solo il nome della relazione, mentre per 
gli attributi ho inserito l'intera segnatura.

Ambedue le notazioni vanno bene, dipende dal motivo e dal contesto in 
cui le usa. Ad esempio, se fosse chiesto di specificare i nomi delle 
relazioni, evidentemente, "{ passa_per, ha_colore, ...}" sarebbe la 
risposta giusta, mentre se venisse chiesto di specificare la segnatura 
di ha_colore, allora andrebbero specificate gli etype.

Io ho inserito la segnatura sull'attributo, perché, se non ricordo male, 
era la prima volta che appariva, mentre le relazioni erano state 
discusse in maggior dettaglio e la segnatura era probabilmente più chiara.

Nel compito non si saranno situazioni di ambiguità su questo genere di 
cose: verrà specificato in domanda che cosa ci aspettiamo.

   cordialmente

   -a
