### ISSUE TITLE
NNF

### ISSUE THREAD

**Issue by AlessandroTomazzolli** [avillafiorita/cl-2020#66]
Buongiorno, non ho capito che cosa si intende con Negative Normal Form: dobbiamo trasformare sempre una formula prima di eseguire un tableaux in DL?

**Comment by avillafiorita** [comment]
NNF è una forma normale meno restrittiva di una CNF. Si ha una NNF quando una negazione è spinta in basso il più possibile nell'albero di parsing. In una NNF, quindi, le negazione nega una formula atomica. 

A differenza di nua CNF, la NNF non richiede di avere solo connettivi AND/OR; basta "spingere" le negazioni.

In un tableaux modale conviene avere una NNF in modo da non avere una negazione davanti ad un operatore modale e quindi poter applicare le regole di apertura del mondo.

**Comment by AlessandroTomazzolli** [comment]
Buonasera, grazie del chiarimento ma continuo a non capire come portare una formula normale in forma NNF

**Comment by avillafiorita** [comment]
not exists R. C -> forall R. not C
not forall R. C -> exists R. not C
Il resto è proposizionale, che dovrebbe già sapere... ad esempio De Morgan per spingere su AND/OR o implicazione con NOT (A IMP B) -> A AND NOT B

forall è la stessa cosa di Box e exists la stessa cosa di Diamond nelle logiche modali

**Comment by avillafiorita** [comment]
(Chiuso, riapriamo se non chiaro)
