### ISSUE TITLE
esercizi DL

### ISSUE THREAD

**Issue by TudiFrudii** [avillafiorita/cl-2020#68]
buongiorno, volevo chiedere se sono previste altre esercitazioni su DL oppure se e' possibile caricare dei nuovi esercizi di esempio su cui lavorare. In particolare sulla formalizzazione da linguaggio naturale.
grazie mille

**Comment by avillafiorita** [comment]
Gli esercizi svolti in video coprono gli argomenti del compito. 

Entro domani valuteremo se dare qualche esercizio in più, comunque sulla falsa riga dei precedenti.

La pagina con i materiali include link ad risorse esterne con esercizi. La aggiorniamo con risorse su ML e DL; avvertiamo dell'aggiornamento con il solito avviso su Moodle.
