### ISSUE TITLE
Dubbio esercizio DL

### ISSUE THREAD

**Issue by AlessandroTomazzolli** [avillafiorita/cl-2020#69]
Buonasera, io e @sav22999 stavamo affrontando il seguente esercizio: 

date:
TBox = {C iff S and T, D iff S and not T}
ABox = {C(a), S(b)}
dimostrare che C e D sono disgiunte

La nostra soluzione prevede di sfruttare la definizione di disgiunzione, e tentare quindi di dimostrare che C and D è contenuto in Bottom. L'approccio è corretto? 
Grazie

**Comment by avillafiorita** [comment]
ragioniamo per assurdo: se a == b, l'espansione contiene T(a) e not T(a) e, quindi, C e D sono disgiunte nell'ipotesi di avere una teroria consistente.

fateci sapere se ok, così chiudiamo

**Comment by AlessandroTomazzolli** [comment]
Buonasera, non riesco a capire quale sia il ruolo delle variabili a e b in questo esercizio, visto che la consegna mi chiede di ragionare su due concetti.

**Comment by avillafiorita** [comment]
I due concetti sono disgiunti se non hanno elementi in comune; il ragionamento sulle costanti permette di ragionare sulla struttura ed eventuale intersezione dei due concetti. 

(Nota nel ragionamento si assume che non valga la unique name assumption, ma, naturalmente, nulla avrebbe impedito di ragionare con un una variabile.)
