### ISSUE TITLE
L3.X.25A.SetTheory.Exercises - SLIDE 8

### ISSUE THREAD

**Issue by StefanoGenettiUniTN** [avillafiorita/cl-2020#7]
Buongiorno.
Nella slide numero 8 della presentazione in oggetto viene chiesto di stabilire se la relazione "next move" sia riflessiva, simmetrica, transitiva, antisimmetrica, suriettiva, iniettiva, abbia un ordine parziale e di cercarne una possibile partizione. Con i modelli logici che ho pensato per rappresentare la relazione mi risulta difficile stabilire la validità o meno di queste proprietà.

Grazie della disponibilità e buon fine settimana.

**Comment by avillafiorita** [comment]
registrazione disponibile sul sito, chiuderei. Chiedere di ri-aprire, se invece il dubbio permanesse.
