### ISSUE TITLE
Instance Retrieval

### ISSUE THREAD

**Issue by AlessandroTomazzolli** [avillafiorita/cl-2020#70]
Buonasera, nello stesso esercizio scritto nella issue #69, il testo chiede di sviluppare la "instance retrieval", in maniera del tutto generica, e senza specificare una query in particolare. In un caso del genere come dobbiamo comportarci? 
Grazie

**Comment by avillafiorita** [comment]
in generale l'instance retrieval è sempre rispetto ad un concetto. Se non fosse specificata andrebbe fatta per tutte le espansioni, in particolare C e D.
Questa eventualità non si pone nel compito, a causa della sua ambiguità.
