### ISSUE TITLE
L21X1

### ISSUE THREAD

**Issue by Sav22999** [avillafiorita/cl-2020#71]
Con @AlessandroTomazzolli stavano riflettendo sull'esercitazione L21X1 e abbiamo notato che, durante lo svolgimento del KG, nello specifico durante la stesura della Abox, non sono stati specificati: `quartiere(zona_fiera)`, `colore(rosso)`, `linea(M1)`, `capolinea(rho)`, `stazione(centrale)`. Non dovremmo inserirli?

Questo perché, nell'esercizio che ha spiegato il prof. Giunchiglia (L19 T165), nella parte di _Instance checking_, venivano elencati nella Abox anche `Horse(Furia)` (minuto 2:27).
![image](https://user-images.githubusercontent.com/32335378/102020173-a135eb00-3d77-11eb-9bf9-fc10b5603910.png)

Grazie

**Comment by avillafiorita** [comment]
Sì, avete ragione, dovreste inserirli. 

Più in generale, che cosa mettete nella vostra TBOX e nella vostra ABOX dipende da cosa volete (o dovete) formalizzare ... in generale dovete mantenere un bilanciamento tra espressività (che però rischia di far "esplodere" la vostra formalizzazione) e "compattezza" (che, però, rischia di limitare o impedire di ragionare su quello che vi serve).

Tornando al video, probabilmente sarebbe stato più chiaro se avessi specificato che l'ABOX contiene tutti i termini ground che identificate.
