### ISSUE TITLE
Dubbio sulla "class valuation"

### ISSUE THREAD

**Issue by Sav22999** [avillafiorita/cl-2020#72]
Con @AlessandroTomazzolli stavamo svolgendo alcuni esercizi degli esami precedenti.
Ci siamo imbattuti nel seguente quesito "Let _σ_ be a class valuation on language L. P is true under _σ_ if..." e il nostro dubbio è sulla definizione di "class valuation", poiché non crediamo sia stata mai citata a lezione. Se può chiarire questo dubbio, per favore.

![image](https://user-images.githubusercontent.com/32335378/102020225-04c01880-3d78-11eb-8a2a-b11b5fa96d29.png)

**Comment by avillafiorita** [comment]
Le slide: http://dit.unitn.it/~ldkr/ml2017/slides/14.DL.Introduction.r03.pdf spiegano il concetto (sigma ritorna l'insieme delle costanti del dominio che rendono vera la formula passata come argomento; funzione di interpretazione, per come è stata definita nella nostra edizione del corso). 

Se il termine non è stato definito a lezione, comunque, non me ne preoccuperei. Gli esercizi presi da risorse esterne e da edizioni precedenti del corso potrebbero contenere argomenti non trattati a lezione.

(Se chiaro, chiuderei)
