### ISSUE TITLE
L18.T153.DL.TBox-ABox.Terminology

### ISSUE THREAD

**Issue by TudiFrudii** [avillafiorita/cl-2020#73]
Buongiorno, ho un dubbio riguardante la correttezza della scrittura di una TBox. 
Sulla seguente slide viene specificato che definizioni e specializzazioni devono essere espresse con un singolo termine sul lato sinistro
![image](https://user-images.githubusercontent.com/61164007/102070783-e140b080-3dff-11eb-9c44-ceafcd2fa0f7.png)
e successivamente si specifica che una TBox e' un insieme delle definizioni e specializzazioni come descritte sopra
![image](https://user-images.githubusercontent.com/61164007/102070839-f74e7100-3dff-11eb-9ebb-710c08ef17b0.png)

Quindi se avessi per esempio 
Father ⊔ Mother ≡ Parent
non sarebbe considerabile una definizione, quindi non sarebbe corretto inserirla in una TBox date le definizioni sopra?

**Comment by avillafiorita** [comment]
se siamo d'accordo sul fatto che le seguenti due formule sono equivalenti:

Father ⊔ Mother ≡ Parent
Parent ≡ Father ⊔ Mother  

basta riscrivere la prima con la seconda e siamo a posto.
