### ISSUE TITLE
L20.T173.X.DL.Applications.KG

### ISSUE THREAD

**Issue by TudiFrudii** [avillafiorita/cl-2020#76]
Buongiorno, nella seguente slide viene riportata la fromalizzazione della frase "Does John have a female friend who has a friend loving a not female?" e mi chiedevo perche' nella formalizzazione, il secondo elemento nella parentesi, presentasse due volte la relazione 'love' mentre non compare mai 'friend'
avrei personalmente formalizzato come segue:
⊨ ∃FRIEND.(Female ⊓ (∃FRIEND. ∃LOVES .¬Female))(john)
la mia formalizzazione e' errata?
![image](https://user-images.githubusercontent.com/61164007/102194483-a604b700-3ebd-11eb-820a-f8b15b1a4c03.png)

**Comment by avillafiorita** [comment]
vado a memoria, c'era un errore nella slide, probabilmente aggiornato 
nel pdf. Comunque ha ragione, la sua formalizzazione è corretta.
