### ISSUE TITLE
Esercizio ML

### ISSUE THREAD

**Issue by Aless1234** [avillafiorita/cl-2020#77]
Buongiorno, in uno dei file dei materiali aggiuntivi che ci avete fornito c'è questo esercizio. Volevo chiedere un chiarimento sul perchè le risposte 3 e 7 sono vere, in quanto a me non risultavano tali.
![image](https://user-images.githubusercontent.com/72376368/102351609-07ed1b80-3fa7-11eb-8453-0302ab87ecbd.png)
Grazie!

**Comment by avillafiorita** [comment]
Buongiorno -

box e diamond sui mondi che non hanno successori sono super-rognosi: box 
phi vale sempre, perche' in tutti gli stati successori (= nessuno stato) 
phi vale; diamond si comporta in maniera opposta (falso, perche' non 
riusciamo a trovare uno stato in cui vale).

Veda anche: https://github.com/avillafiorita/cl-2020/issues/62

spero chiarisca, se così fosse chiuda la issue.

     cordialmente

**Comment by Aless1234** [comment]
Sisi, grazie mille, ho capito!
La ringrazio del chiarimento!
