### ISSUE TITLE
Dubbio su Tbox e Abox

### ISSUE THREAD

**Issue by Sav22999** [avillafiorita/cl-2020#78]
È possibile avere una Tbox vuota e una Abox con degli elementi?
Questo dubbio perché, per definizione, una Abox è riferita sempre a una Tbox. Quindi, vorrei capire se una Abox può contenere elementi ma, comunque, essere rispetto a una Tbox vuota.

Grazie.

**Comment by avillafiorita** [comment]
In linea di principio direi che è possibile, ma non molto utile. 
Che cosa farebbe con la sola ABOX?

**Comment by Sav22999** [comment]
@avillafiorita Esatto, quindi essenzialmente non avrebbe senso, anche se può esistere. Proprio ciò che volevo capire. La ringrazio 😄
