### ISSUE TITLE
Dubbio esercizio DL

### ISSUE THREAD

**Issue by nicolazilio0** [avillafiorita/cl-2020#79]
![Cattura](https://user-images.githubusercontent.com/67425578/102464754-0aa24c00-404d-11eb-9ba5-75d3d2365f47.PNG)

Cercando di formalizzare questo schema  ho due dubbi:
 1) Nello Schema level gli attributi in base a cosa vanno definiti? Devo supporre io che vi siano degli attributi (es. frequenza nell'esempio delle stazioni?) 
2) La relazione di is-a posso vederla come un assegnazione di un valore ad un entity type? in tal caso devo segnarlo all'interno dello schema o semplicemente lo inserisco all'interno dei vari relation values?

**Comment by avillafiorita** [comment]
Buongiorno

1. il processo di modellazione tipicamente procede analizzando il
dominio e identificando quei concetti e quegli attributi che sono utili
per gli obiettivi che si hanno. Ad esempio, se il mio obiettivo fosse
quello di fornire un servizio informativo sui tempi di percorrenza,
potrei introdurre nella mia modellazione il tempo di percorrenza tra due
stazioni, da usare poi per ragionare su quale sia il percorso più
rapido. Il processo, però, è lungo e laborioso e difficilmente
replicabile in un esercizio, dove ho fatto qualche ipotesi, per
presentare alcuni esempi.

2. su questo punto sono stato forse leggermente ambiguo: IsA (o is_a)
rappresenta il concetto di "appartenza", "sussunzione", "essere parte
di".  Nella connessione fra SKG e DKG, l'entità è solitamente
"agganciata" all'entity type attraverso "InstanceOf"; io ho "abusato"
della notazione utilizzando "IsA" al posto di instance of.  Il concetto,
comunque, non cambia e il compito sarà chiaro nel distinguere, nelle
domande, tra SKG e DKG.

spero aiuti, nel caso ci sentiamo, altrimenti se è tutto a posto, chiuda
la issue.

  cordialmente
  -a

nicolazilio0 writes:

> ![Cattura](https://user-images.githubusercontent.com/67425578/102464754-0aa24c00-404d-11eb-9ba5-75d3d2365f47.PNG)
>
> Cercando di formalizzare questo schema  ho due dubbi:
>  1) Nello Schema level gli attributi in base a cosa vanno definiti? Devo supporre io che vi siano degli attributi (es. frequenza nell'esempio delle stazioni?)
> 2) La relazione di is-a posso vederla come un assegnazione di un valore ad un entity type? in tal caso devo segnarlo all'interno dello schema o semplicemente lo inserisco all'interno dei vari relation values?

**Comment by nicolazilio0** [comment]
Il punto 1 mi è chiaro ora; 
Riguardo al punto 2 invece mi rimane un dubbio,  la relazione "InstanceOf" va quindi riportata all'interno della parte di SL e poi nella parte di DL faccio le associazioni 
es. SL relations: <etype,etype> InstanceOf....
     DL Relation Values: InstanceOf(Student,Person) ...



Inoltre mi è sorto un altro dubbio : vi è un ordine preciso all'interno degli etype di una relation? es. rides_a(person,bike) rides_a(bike, person)  hanno entrambe senso in base all'interpretaizione che do all'ordine, Per non essere ambigui ha senso seguire il verso delle relazioni?

**Comment by avillafiorita** [comment]
IsA diventa sussunzione ne SKG (Student <= Person); nel DKG diventa una formula Student(Mary)
