### ISSUE TITLE
Teoria,Assiomi e Chiusure

### ISSUE THREAD

**Issue by Aless1234** [avillafiorita/cl-2020#8]
Volevo chiedere se potrebbe rispiegare i concetti di teoria, assioma e chiusure e come questi sono collegati. ( non ho delle slide specifiche che non ho capito, non ho proprio capito il concetto che sta alla base di queste tre definizioni)
Inoltre volevo chiederle: all'esame potremmo tenere lo schema che ci aveva mostrato per la riduzione in cnf di una formula? potremmo tenere lo schema dei tableaux per sapere come aprire congiunzioni e disgiunzioni nell'albero ?

**Comment by avillafiorita** [comment]
discusso a lezione, chiuderei. Chiedere di ri-aprire, se invece il dubbio permanesse.
