### ISSUE TITLE
Dubbi domanda 3 seconda provetta

### ISSUE THREAD

**Issue by simoneruffini** [avillafiorita/cl-2020#83]
Guardando le correzioni della domanda 3 sono sorti alcuni dubbi:
1)nella classe dei frame simmetrici C, se A è nella forma B⊃□ ¬ □ ¬ B 
Questa risposta e' segnata come errata pero' B⊃□ ¬ □ ¬ B e' equivalente a B⊃□♢B ossia la conseguenza logica del frame simmetrico. Quindi a mio parere tale risposta sarebbe giusta.
2)nella classe dei frame seriali C, se e solo se F ⊨ A per ogni F = <W, R> e, per ogni w ∈ W, esiste w ′ tale che R(w, w′)
Questa domanda a mio parere e' malposta in quanto dice: nei frame seriali se A e' valida allora siamo in un frame seriale ; oppure leggendola nell'altro verso: dato A valido  nel frame seriale allora siamo in un frame seriale.
Benche' questa formulazione ha """senso""" (perche' nella forma A imp A) non saprei se considerare questa domanda corretta.

Mi faccia sapere!

**Comment by avillafiorita** [comment]
Per quanto riguarda il punto 1, l'argomentazione sembra corretta e ci riserviamo di riverificare i pesi assegnati alla risposte. 

Per quanto riguarda il punto 2, ringraziao per il feedback.
