### ISSUE TITLE
Domanda 5 Seconda Provetta

### ISSUE THREAD

**Issue by ericsua** [avillafiorita/cl-2020#84]
Non mi torna la correzione della domanda 5 nella seconda provetta:
le risposte corrette del tableaux secondo la correzione sono: valido e soddisfacibile, mentre secondo me e secondo il sito posto nella sezione "Additional Materials" [https://www.umsu.de/trees/](https://www.umsu.de/trees/) , la formula risulta soddisfacibile ma non valida

<img width="829" alt="image" src="https://user-images.githubusercontent.com/33501092/103221542-3661e380-4923-11eb-859f-0b4f6330c925.png">

**Comment by avillafiorita** [comment]
esatto, a questo le rispondo subito: ha ragione.

Abbiamo pensato di garantire anche un minimo voto positivo a chi avesse 
risposto valida (scorrettamente), al posto di soddisfacibile (risposta 
corretta). Per fare questo abbiamo "alterato" il peso assegnato alla 
risposta "valida", che, diventato positivo, marca la risposta come corretta.

**Comment by simoneruffini** [comment]
Si ma questo penalizza chi ha perso tempo a capire che il tableaux fosse effettivamente valido

**Comment by avillafiorita** [comment]
quindi sta suggerendo di togliere i punti che abbiamo assegnato a chi ha 
risposto 'valido'?

**Comment by matteo-gatti** [comment]
quello che dice Simone è che Lei in questo modo favorisce chi sbaglia e penalizza chi risponde correttamente alla domanda.. dare punti a chi ha risposto "Valido" per come è stato strutturato l'esame va a togliere punti da tutti quelli che hanno ragionato fino a fondo per provare il tableaux non valido. 

e per principio avere la risposta corretta "incorretta" sembra poco logico..

**Comment by avillafiorita** [comment]
Quanto dice, così come quello che dice il suo collega è comprensibile. 
Il punto è che cosa avrebbe fatto, perché ritengo che la risposta non 
sia ovvia e che sia un utile esercizio di ragionamento su cosa sia 
giusto e cosa no.

Le dico che cosa abbiamo fatto noi, constatato che la prima valutazione 
era risultata in voti molto bassi:

a. Abbiamo alzato il voto totale del compito a 37.00

b. Siamo entrati nel merito di ogni risposta, rivalutando il compito e:

1. Azzerando o riducendo significativamente i pesi negativi

2. (in qualche caso) assegnando un punteggio positivo ad una risposta 
errata, ma non troppo distante da quella vera

Questo ha consentito di portare la valutazione del voto a medie e 
varianze "ragionevoli" e, soprattutto, di farlo entrando nel merito di 
domande e risposte (o almeno così crediamo); cosa che non avremmo potuto 
ottenere ricorrendo ad un fattore esclusivamente additivo (aggiungo 7 
punti ai voti) o moltiplicativo (moltiplico i voti per 1.7).

Venendo al dunque della questione, constatato che Moodle NON consente di 
assegnare il 120% ad una risposta, la conseguenza di 2 sulla domanda del 
Tableau---in cui abbiamo deciso di assegnare 80% alla risposta corretta 
e 20% a quella errata---è la seguente:

- Abbiamo assegnato un punteggio positivo a risposte errate, garantendo 
un ingiusto vantaggio a chi ha risposto male. In questo caso, il 
comportamento corretto sarebbe quello di azzerare il punteggio assegnato.

- Abbiamo "penalizzato" chi ha risposto correttamente, assegnando un 
punteggio minore di quello indicato sul quiz. Noti però che la 
"penalizzazione" è, appunto, rispetto al punteggio mostrato sul test. Si 
potrebbe argomentare che il voto indicato sull'esercizio deve far fede, 
ma questo ci avrebbe impedito di cambiare anche il voto totale assegnato 
al compito. Noi abbiamo invece preferito cambiare il voto massimo 
(portandolo a 37) e assegnare un peso minore all'esercizio del Tableau 
rispetto al resto del compito (calando il massimo da 4 a 3 punti).

**Comment by matteo-gatti** [comment]
Ora capisco il motivo delle scelte adoperate, grazie del chiarimento.

A mio avviso, dato che a priori l'esame è stato sviluppato in modo da penalizzare per una risposta non corretta la scelta è unica: assegnare il punteggio corretto alle risposte giuste, senza andare a modificare il resto.
Questo sempre per una questione di "principio" in quanto non riesco a immaginare una situazione in cui una risposta errata possa ricevere più punti di una risposta corretta.
(prima opzione)

Quello che mi verrebbe da proporre (senza conoscere a fondo il funzionamento di moodle) è di assegnare il punteggio pieno a chi da la risposta corretta e assegnare una frazione del punteggio a chi segna anche/solamente l'opzione "valido"
In questo modo non viene penalizzato lo studente che risponde correttamente e lo studente che risponde parzialmente corretto ha comunque una frazione del voto ma mai un voto superiore alla risposta corretta.
(seconda opzione)

Sfortunatamente il ragionamento della seconda opzione va in conflitto con la politica dell'esame stesso di avere ogni risposta giusta che vale come frazione del punteggio massimo dell'esercizio e ogni risposta sbagliata che vale negativamente per una frazione del punteggio (in base al numero di risposte giuste/sbagliate, come espresso nelle linee guida dell'esame).

In definitiva, date le linee guida dell'esame e quanto discusso in precedenza, se dipendesse da me opterei per la prima opzione.

Ovviamente sono solo uno studente e non posso darLe dei suggerimenti, volevo solamente rispondere alla questione del "cosa avrei fatto" che ha presentato nel commento precedente.
Buona serata

**Comment by simoneruffini** [comment]
Se moodle non riesce a gestire bene la correzione o l'assegnamento dei punteggi non e' possibile scaricare gli esiti e gestirli per esempio da uno spreadsheet? Per esempio nel caso di questa domanda darebbe la possibilita' di assegnare punteggi diversi in base a come e' stata data la risposta, il punteggio massimo a chi ha risposto solo alla risposta giusta e qualcosina per quelli della risposta sbagliata. In modo che la domanda valga sempre lo stesso punteggio e non deve  valere al 120%.

**Comment by avillafiorita** [comment]
Abbiamo analizzato le vostre argomentazioni, che riteniamo corrette. 

Seguirà una rivalutazione dei compiti.
