### ISSUE TITLE
Dubbi domanda 6 seconda provetta

### ISSUE THREAD

**Issue by simoneruffini** [avillafiorita/cl-2020#85]
Su questa domanda e' nato un dubbio su una possibile soluzione:
![image](https://user-images.githubusercontent.com/50401154/103224869-e8e87500-4928-11eb-8d41-483d460a648b.png)
Se nei knowledge graphs vale la close world assumption, non dovrebbe valere anche questa 
![image](https://user-images.githubusercontent.com/50401154/103224881-f30a7380-4928-11eb-9d08-f9cead31b348.png)

**Comment by ericsua** [comment]
Anche secondo me dovrebbe essere corretto, c'è un esempio molto simile alla slide 5 del PDF L20.T172.X.DL.Applications.ERModels.pdf, dove Person ⊑ Manager ⊔ Employee


<img width="801" alt="image" src="https://user-images.githubusercontent.com/33501092/103234312-ab431680-493f-11eb-892f-f582719a5939.png">

**Comment by avillafiorita** [comment]
La CWA non vale di "default" per nessun tipo di logica e, quindi, in particolare, per i DKG. Quindi la CWA deve essere dichiarata esplicitamente per valere.

La slide presentata non applica al caso in questione, in quanto la notazione utilizzata è quella degli ER diagram quindi diversa da quella della domanda.

**Comment by ericsua** [comment]
Non capisco perché la rappresentazione mammifero ⊑ balena ⊔ leone  sia sbagliata, in questo particolare caso non abbiamo istanze di altre specializzazioni di mammiferi oppure istanze dirette di mammiferi (ad esempio mammifero(x)). Perciò non vedo quale possa essere l'errore in questa rappresentazione.
