### ISSUE TITLE
L7.T52.PL.Hilbert Calculus

### ISSUE THREAD

**Issue by notyourbusiness-afk** [avillafiorita/cl-2020#9]
Buongiorno, nella lezione prevista per il 6/10, è presente un esempio di deduzione e come esercizio dobbiamo costruire l'albero che deriva dalla deduzione. Non ho ben capito come va rappresentato l'albero.
Inoltre non mi sono ben chiare le regole di inferenza (es. Modus Pollens, Modus Tollens,..), anche queste presentate brevemente durante la lezione del 6/10.

**Comment by avillafiorita** [comment]
discusso a lezione, chiuderei. Segnalare invece se il dubbio permanesse.
